### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by pianocomposer321**
I made this branch because the codebase was (no offence) an unmitigated mess. Almost all the code was in the same file, and everything was coupled together so that you couldn't start a ripgrep process without creating a Buffer. This PR separates out the code for Buffer into its own file, and adds a Search object that is separate and can be used independently. In practice, this means that the Search class acts as a back end, and the Buffer acts a front end. This will make it much easier to add any new features, particularly features involving changing or adding UIs.

I realize that the changes made are very opinionated, and I will not be offended if you want some of them changed or just don't accept the PR at all. But contributing to the repo in the state its currently in is going to be a nightmare, and so if this PR is not merged I think I will end up just maintaining my own fork from this point forward.

A summary of the changes:
 - The `:Rg` command calls an autoload function (`ripgrep#search(options, pattern)`), which internally calls `ripgrep.search(options, pattern)` in ripgrep.lua, instead of the behavior being hard-coded
 - Logic in the Buffer class that is actually UI-specific is separated out into the buffer.lua file, and the logic that isn't is either kept in ripgrep.lua or put in the new search.lua file.
 - Oh, and instead of being global, the `ripgrep` object is returned from ripgrep.lua just like every other lua project ever ;-).

### CODE REVIEW

**Comment by frangio** [comment]
I appreciate the critique but calling it an "unmitigated mess" is indeed a little bit offensive. :slightly_smiling_face: 

Thanks for the PR though, I'll take a look.

**Comment by pianocomposer321** [comment]
> I appreciate the critique but calling it an "unmitigated mess" is indeed a little bit offensive. 
> 
> Thanks for the PR though, I'll take a look.

I apologize, I really didn't mean to be offensive. I know that you made this project just for your own personal use, and I really do appreciate you posting it on github. I learned a lot just by looking through the codebase (for example, I never knew about the lua module `vim.loop` until I saw this plugin), and I never would have been able to build this from scratch. I also know that when you make a project for yourself you have a limited set of functionality that you want to accomplish (or at least I do), and over-engineering the code normally makes those goals harder to reach. But if you want to expand on the functionality at all (which I do want to do), refactoring once you are past that point is, I'm sure you will agree, necessary. I simply wanted to give you the reasons for the PR straight, and now I realize I could have been more tactful, so I apologize for that. I wasn't saying it as a criticism to you as a programmer or even the project as a whole. I was simply stating that there was a problem (even if it wasn't a problem when the repo was created, it will be if we want to expand), and that this PR is here to try to fix it.

**Comment by pianocomposer321** [comment]
Oh, and by the way, this PR includes all the changes that are in the other PR (https://github.com/frangio/ripgrep.nvim/pull/3). I'm not a Git expert, so I probably went about this the wrong way; I don't know whether it will mess anything up if the other PR is merged before this one...hopefully you know more about how Git works than I do :grin:.

**Comment by frangio** [comment]
Definitely agree with everything you said!

**Comment by frangio** [comment]
I removed the `Search` module because I felt that the separation of concerns wasn't very neat. But I added a new layer on top of `spawn` to make `Buffer` more focused. And based on your suggestions I also moved all of the utility functions to separate files to make everything more structured.

I may merge this as is but do leave any comments if you have some!

**Comment by pianocomposer321** [comment]
@frangio Thanks for reviewing and merging. Sorry I didn't respond sooner, my computer's hard drive crashed and then I was gone on vacation for 3 weeks so I was only just now able to get to the point where I was logged back in to github and able to respond.

Looks good!

**Pull request merged**
